version: '3'

services:
  web:
    build: .
    ports:
      - "5005:80"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: voting_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
