apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-config
  namespace: default
data:
  POSTGRES_DB: mydatabase  # Adjust to your PostgreSQL database name
  POSTGRES_USER: myuser    # Adjust to your PostgreSQL username
  POSTGRES_HOST: postgres-service  # Adjust to your PostgreSQL service name or IP address


