apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-deplo
  template:
    metadata:
      labels:
        app: web-app-deplo
    spec:
      containers:
        - name: web-app
          image: "your image of app"
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
          env:
            - name: POSTGRES_USER  # Adjust for PostgreSQL
              valueFrom:
                secretKeyRef:
                  name: admin
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD  # Adjust for PostgreSQL
              valueFrom:
                secretKeyRef:
                  name: password
                  key: POSTGRES_PASSWORD
    
