# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Box settings
    config.vm.box = "hashicorp/precise64"
  
    # Network settings
    config.vm.network "forwarded_port", guest: 80, host: 8080
  
    # Provider-specific settings
    config.vm.provider "vmware_fusion" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  
    # Provisioning
    config.vm.provision "shell", inline: <<-SHELL
      # Update the package repository
      sudo apt update
      sudo apt upgrade
  
      # Install additional packages if needed
      # sudo apt-get install -y your-package-name
  
      # Clean up
      sudo apt autoremove -y
      sudo apt clean
    SHELL
  end
  